### ISSUE TITLE
Eliminate org, except Matl. 

### ISSUE THREAD

**Issue by calvinc460** [calvinc-org-10/WICS-3#1]
This issue was: Let users choose org

**Comment by calvinc460** [comment]
Count Summary - list all orgs

Moved to issue #64

**Comment by calvinc460** [comment]
org is only tied to Material.  Do not tie user to org, but let them work with all Material.  If Material in multiple orgs, do <select> for desired org.

Count Summary: group by org

**Comment by calvinc460** [comment]
- [x] add org to CountEntry Spreadsheet for Material with more than one org (#1)

**Comment by curtindolph-calvin-10** [comment]
Code to check/modify:

WICS:
- [x] dbVIEWS.sql (don't forget the views in models.py)
- [x] forms.py - look at class RequestCountScheduleRecordForm/save
- [x] globals.py
- [x] models.py (1st pass done, return after views changed and other changes)
- [x] procs_ActualCounts.py
- [x] procs_CountSchedule.py
- [x] procs_Material.py
- [x] procs_misc.py
- [x] procs_SAP.py
- [x] userinit.py
- [x] views.py

userprofiles:
- [x] globals.py
- [x] login.py
- [x] logout.py
- [x] models.py
- [x] pwd.py
- [x] views.py (first pass done , anyway)

cMenu:
- [x] models.py
- [x] utils.py
- [x] views.py

**Comment by calvinc460** [comment]
- [x] In templates, replace uname with user.get_full_name

**Comment by curtindolph-calvin-10** [comment]
Done. Code completely reworked, replaced existing code on GitHub.  Will move to prod after a few more issues handled.
