### ISSUE TITLE
Upload MM60 async progress meter

### ISSUE THREAD

**Issue by calvinc460** [calvinc-org-10/WICS-3#130]

**Comment by curtindolph-calvin-10** [comment]
Timing issues in the resync, especially on the deletes.  Issue reopened

**Comment by curtindolph-calvin-10** [comment]
REVIEW CODE AGAIN!!
Should these be the transitions?

after read
--> (synchronously)
pt 2 (continue polling)
--> on stat: get-matl-link-done
pt 3 (continue polling, even if stat: done ???)
--> stat:
