### ISSUE TITLE
SAP_SOHrecs field changes

### ISSUE THREAD

**Issue by calvinc460** [calvinc-org-10/WICS-3#131]
- [x] Material -> PartNum
- [x] MatlRec -> Material
This last change is the reason for this issue - so that the naming is standard across ALL tables
This anomaly is leading to mucho bugs - Material is the pointer, except for...  -- not good

**Comment by calvinc460** [comment]
Profile this code - Material List taking way too long

**Comment by curtindolph-calvin-10** [comment]
The problem wasn't the SAP_SOHrecs changes.  It was in the LastFoundAt views.  The SQL Django constructed had subqueries inside of subqueries, which was running wayyy too slow.  Changed to JOINS/rawsql/dictfectchall.  Could be tweaked, but now the big MaterialList reports finish before PythonAnywhere timeout.

This issue will be closed when I push the commit.
