### ISSUE TITLE
Embed DEV ver/PROD ver in code.

### ISSUE THREAD

**Issue by calvinc460** [calvinc-org-10/WICS-3#14]

**Comment by calvinc460** [comment]
Announce in WICS-News or login main screen.  Code in django_settings?

**Comment by calvinc460** [comment]
Nope - code in WICS.sysver.py.  Try:
sysver = {'DEV': '3.a', 'PROD':'3.0'}  place key to use in django_settings

**Comment by curtindolph-calvin-10** [comment]
Implemented in WICS2/issue #36
