### ISSUE TITLE
Is mult being used correctly?

### ISSUE THREAD

**Issue by calvinc460** [calvinc-org-10/WICS-3#14]
See Material Form, part G1054205, Counts and Count Summary

**Comment by calvinc460** [comment]
<img width="960" alt="image" src="https://github.com/calvinc-org-10/WICS-3/assets/104769898/a78a92b9-5274-4b4e-9284-c139865878f0">

**Comment by curtindolph-calvin-10** [comment]
Yes it is.  The problem in this specific instance is that the "count" came directly from SAP, which reports in KPC.  A real count would have counted EA.

**Comment by curtindolph-calvin-10** [comment]
No, mult is not honored in the Actual Count Summary of the Material Form.  Issue reopened

**Comment by calvinc460** [comment]
Ct Worksheet - is SAPQty multiplied?

**Comment by curtindolph-calvin-10** [comment]
- Confirmed that mult is used for SAP Amounts on Material Form (issue https://github.com/calvinc-org-10/WICS-3/issues/14)

**Comment by calvinc460** [comment]
No glaring instances where mult is not used.  Closing this issue
