### ISSUE TITLE
Count Request: Form doesn't detect already scheduled date/material

### ISSUE THREAD

**Issue by calvinc460** [calvinc-org-10/WICS-3#49]
<img width="961" alt="image" src="https://github.com/calvinc-org-10/WICS-3/assets/104769898/a73b68a2-b803-48e3-92ab-bcf2c29e9a13">

**Comment by calvinc460** [comment]
Same thing happening with Count Schedule Form

**Comment by curtindolph-calvin-10** [comment]
fnCountScheduleRecordExists was trying to get Material (the GPN string) = Matl (passed in) even if the record number was passed in.  Added type test and get pk=Matl if Matl is int
