### ISSUE TITLE
Give more info in Count record saved alert

### ISSUE THREAD

**Issue by calvinc460** [calvinc-org-10/WICS-3#5]
Instead of
Count record 8696 successfully saved. ChData: ['CountDate', 'Counter', 'BLDG', 'LOCATION', 'CTD_QTY_Expr', 'Material']
go for
Count record 8696 (2023-03-24 / 1121212-12 / Calvin / HVC_TwilightZone) successfully saved.

**Comment by curtindolph-calvin-10** [comment]
Done in rewrite to WICS3
